---
title: "Plot a Map in R"
description: |
  Verschiedene Möglichkeiten der Kartendarstellungen
author:
  - name: M. Hense
    url: {}
date: 2023-10-31
output:
  distill::distill_article:
    self_contained: false
editor_options: 
  markdown: 
    wrap: 72
---

```{r}
library(leaflet) 
leaflet() %>%  
 addTiles() %>%  
 addMarkers(lng = 11.101, lat = 51.356, 
            popup = "Standort")
```

```{r}
library(sp)
df <- data.frame(long = c(11.101),
                 lat = c(51.356),
                 label = c('Bad Fankenhausen'))
                
coordinates(df) <- ~ long + lat
class(df)

```
```{r}
autoplot(df, p = p, colour = 'red', size = 10)
```

```{r}
library(mapview) 

# Create example data of points 
lng <- c(11.101,10.871 , 11.411) 
lat <- c(51.356, 51.369, 51.266) 
names <- c("Bad Frankenhausen", "Sondershausen", "Wiehe") 

# Create a data frame with the point data 
points_df <- data.frame(lng, lat, names) 

# Convert the data frame to a spatial points data frame 
points_sdf = sf::st_as_sf(points_df, 
				coords = c("lng", "lat"), crs = 4470) 

# Plot the points on a map 
mapview(points_sdf, label = points_sdf$names)
```




```{r}
# Load required packages
library(ggplot2)
library(sf)
library(maps)

# Load and plot world map data - oder world ohne Landesangabe
world <- map_data("world2", "Germany")

ggplot(data = world, aes(x = long, y = lat, group = group)) +
# Farbe aendern  
  geom_polygon(fill = "grey", color = "grey1") +
# aendert die Plotgröße  
  coord_fixed(ratio = 1) +
labs(title = "Deutschland")

```


```{r}
library(ggfortify)
de <-  map('world2', 'Germany', plot = FALSE, fill = TRUE)
autoplot(de)
```

```{r}
de1 <- autoplot(de, geom = 'polygon', fill = 'subregion') + 
  theme(legend.position="none")
de1
```


```{r}
cities <- get('world.cities')
cities <- cities[cities$country.etc == 'Germany', ]
head(cities)
```

```{r}
# Städte und Inseln 
de1 + geom_point(data = cities, aes(x = long, y = lat),
               colour = 'blue', size = 0.1)
```